vim.cmd[[:hi Vimwikiheader1 guifg=#f7768e]]
vim.cmd[[:hi Vimwikiheader2 guifg=#9ece6a]]
vim.cmd[[:hi Vimwikiheader3 guifg=#e0af68]]
vim.cmd[[:hi Vimwikiheader4 guifg=#7aa2f7]]
vim.cmd[[:hi Vimwikiheader5 guifg=#bb9af7]]
vim.cmd[[:hi Vimwikiheader6 guifg=#7dcfff]]
